const urls = {
  PRODUCTS: "products",
  CATEGORIES: "categories",
  SLUGIFY: "slugify",
  SLUGS: "slugs",
  PRODUCT: "product",
  AUTH: "auth",
  LOCAL: "local",
  REGISTER: "register",
  USERS: "users",
  ORDERS: "orders",
  ORDER_DETAILS: "order-details",
  PRODUCT_SELETIONS: "product-seletions",
  BLOGS: "blogs",
  BLOG: "blog",
  CATEGORY: "category",
  CATEGORY_SELECTIONS: "category-selections",
  CATEGORY_SELECTION: "category-selection",
  FEEDBACKS: "feedbacks",
  ME: "me",
  PAYMENT_CRATE: "create_payment_url",
  ROOM_CHATS: "room-chats",
  MESSAGES: "messages",
};
export default urls;
